version: '3.8'

services:
  web:
    build: .
    container_name: traderamp-web
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Optional: Local development with live reload
  # Uncomment to use a simple Python server instead of nginx for development
  # dev:
  #   image: python:3.9-alpine
  #   container_name: traderamp-dev
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   command: python -m http.server 8000
  #   restart: unless-stopped